### ISSUE TITLE
backports to 8_0_X for legacy re-reco of 2016 data

### ISSUE THREAD

**Issue by jan-kaspar** [CTPPS/cmssw#11]
There is a "continuous integration" branch to collect backports needed for the re-reco of 2016 data:
  https://github.com/CTPPS/cmssw/tree/ctpps_cumulative_backport_8_0_X
This branch is to be submitted shortly before the re-reco campaign, a preliminary date is 27 Feb. This issue is to track the changes so as the PR can be submitted promptly.

The branch includes backports of
  * #16010 : detector id update
  * #16616 : raw-to-digi for diamond detectors
  * #17424 : miniAOD (resubmitted); **TODO**: this should be changed to #17701 including the latest commits
  * #17535 : geometry (+rec hits) for diamond detectors, geometry thread-safe; ONLY partly back-ported yet

**Comment by forthommel** [comment]
The latest changes introduced after all discussions in the various PR pages are now cherry-picked in this cumulative backport branch (see commit https://github.com/CTPPS/cmssw/commit/76dd085b18774182ba1389c308cf4774f3453225).

In case the diamond local tracks reconstruction (i.e. #17558) is chosen not to be present in this global backport, another branch (https://github.com/CTPPS/cmssw/tree/ctpps_cumulative_backport_nodiamltreco_8_0_X) has been defined for https://github.com/cms-sw/cmssw/pull/17535/commits/8083280809638dff8dbde5faf4f1ec63bade0f6f.

**Comment by forthommel** [comment]
Backport pull request was just opened: #17815
