### ISSUE TITLE
PPS activities foreseen for a calm period

### ISSUE THREAD

**Issue by jan-kaspar** [CTPPS/cmssw#40]
***IMPORTANT***: the list below is now deprecated and replaced by this [Google sheet](https://docs.google.com/spreadsheets/d/1Yv_2uDdqvFGLTjspm60fnUMQfLr3geuNF_xXfpd_uWI/edit?usp=sharing)

# Deprecated list

* geometry update:
   * https://github.com/cms-sw/cmssw/issues/25434, consider also #12
   * fix the geometry of diamonds: LHC sector 45 should have z negative
   * remove dependence on `CLHEP`, cf. https://github.com/cms-sw/cmssw/pull/25495#pullrequestreview-218990266
   * check that RP (scoring plane) z position is the same for pixels, strips and optics
   * migration to DD4Hep

* systematic renaming
  * ``CondFormats/CTPPSReadoutObjects`` --> ``CondFormats/CTPPSObjects``
  * CTPPS --> PPS, also discussed in #25690

* move ``Validation/CTPPS/python/year_2016/randomXiThetaGunProducer_cfi.py`` to ``Configuration/Generator`` in order to have a reference for PPS proton gun-like simulation. Cf. https://github.com/cms-sw/cmssw/pull/25495#pullrequestreview-219923984

* optimizations
  * systematic use of ``edm::DetSetVector::emplace_back``, see https://github.com/cms-sw/cmssw/pull/26069

* add analytic/iterative proton-reconstruction algorithm

* think about "re-alignment" possibility on the level of lite tracks - this would allow re-applying alignment on MINIAOD data

* clean/organise files in ``Geometry/VeryForwardData/data``, at least separate simulation and reconstruction geometry

* DQM
   * separate "source" and "harvesting" sequences - in offline DQM they're run separately
   * diamond module - some code needs to be moved to a harvesting module
   * selection of plots for online and offline DQM

* direct simulation: push updates to official CMSSW
  * first to CMSSW 11, then backport to 10

# Already completed
* data-format API change: no "get" prefix for getters (issue #25690), addressed in PR #28252

**Comment by clemencia** [comment]
So will it be CondFormats/CTPPSReadoutObjects to CondFormats/PPSObjects ?

**Comment by forthommel** [comment]
Another possible attosecond-scale timing/performance improvement may be through the use of `emplace_back` instead of constructor+`push_back` to `edm::DetSetVector`s, as suggested in https://github.com/cms-sw/cmssw/pull/26069. Again, maybe a longer term development...

**Comment by forthommel** [comment]
> > So will it be CondFormats/CTPPSReadoutObjects to CondFormats/PPSObjects ?
> 
> This is my idea - it follows the guidelines, right?

I guess that https://github.com/cms-sw/cmssw/pull/25495/commits/adf2afb1af910e6f01ef4d7e577a18d230eb60d3 makes it more a `CalibPPS/ESProducers`, right?

**Comment by jan-kaspar** [comment]
> Another possible attosecond-scale timing/performance improvement may be through the use of `emplace_back` instead of constructor+`push_back` to `edm::DetSetVector`s, as suggested in [cms-sw#26069](https://github.com/cms-sw/cmssw/pull/26069). Again, maybe a longer term development...

Added to the list, thanks!

**Comment by jan-kaspar** [comment]
> > > So will it be CondFormats/CTPPSReadoutObjects to CondFormats/PPSObjects ?
> > 
> > 
> > This is my idea - it follows the guidelines, right?
> 
> I guess that [cms-sw@adf2afb](https://github.com/cms-sw/cmssw/commit/adf2afb1af910e6f01ef4d7e577a18d230eb60d3) makes it more a `CalibPPS/ESProducers`, right?

In my understanding these are two different things
  * `CondFormats/PPSObjects`: for data formats
  * `CalibPPS/ESProducers`: for producers/plugins

Am I mistaken?

**Comment by forthommel** [comment]
Indeed, I was not so clear... I meant the `CondFormats/CTPPSReadoutObjects/plugins` part of this sub-package (since we are the only group with the `ESProducers` defined inside `CondFormats`). But indeed, it seems strange to have objects such as pixels DAQ mapping inside a `CalibPPS` package... To be investigated.

**Comment by jan-kaspar** [comment]
> Indeed, I was not so clear... I meant the `CondFormats/CTPPSReadoutObjects/plugins` part of this sub-package (since we are the only group with the `ESProducers` defined inside `CondFormats`).

Indeed, this is forbidden and we should fix it.

**Comment by jan-kaspar** [comment]
The TODO list has been moved to a Google doc.
