### ISSUE TITLE
Redesign of EventSetup handling of optical functions

### ISSUE THREAD

**Issue by jan-kaspar** [CTPPS/cmssw#41]
Here is a proposed ES structure for handling optical functions, based on two ES records.

 * ``CTPPSOpticsRcd``
   * does not depend on anything
   * contains optical functions for two values of crossing angle = source data for interpolation, class ``LHCOpticalFunctionsCollection``
   * built by ``CTPPSOpticalFunctionsESSource`` (from ROOT file) or later from condDB

```
class LHCOpticalFunctionsCollection
{
  double m_xangle1, m_xangle2;
  unordered_map<unsigned int, LHCOpticalFunctionsSet> m_functions1, m_functions2; // RP id --> optical functions
};

class LHCOpticalFunctionsSet
{
  // only data that should be stored in DB
  double m_z;
  std::vector<double> m_xi_values;
  std::array<std::vector<double>, 16> m_fcn_values;
};
```

 * ``CTPPSInterpolatedOpticsRcd``
   * depends on LHCInfoRcd (crossing angle) and CTPPSOpticsRcd (source data for optics interpolation), thus interpolation invoked at relevant input data changes
   * contains optical functions for the current crossing angle and with splines initialised, class ``unordered_map<unsigned int, LHCInterpolatedOpticalFunctionsSet>``
   * built by ``CTPPSInterpolatedOpticalFunctionsESSource``

```
class LHCInterpolatedOpticalFunctionsSet : public LHCOpticalFunctionsSet
{
  // adding splines for run-time performance
  std::array<std::shared_ptr<const TSpline3>, 16> m_splines;
};
```

**Comment by jan-kaspar** [comment]
@wpcarvalho Would it be possible to generalise as follows?
```
class LHCOpticalFunctionsCollection
{
  // map: xangle --> (map: RP id --> optical functions)
  std::map<double, std::unordered_map<unsigned int, LHCOpticalFunctionsSet>> m_data;
};
```
In other words, can the DB store the optical functions at a variable number of crossing angle points?

**Comment by wpcarvalho** [comment]
Thinking about the new design...

**Comment by wpcarvalho** [comment]
In this design LHCOpticalFunctionsSet would be a standard DB class with its associated record LHCOpticalFunctionsSetRcd what seems OK.

On the other hand, a CTPPSOpticsRcd would imply a CTPPSOptics DB class, which I believe would have to follow the requirements for such classes like being serializable. Probably the same is true for LHCOpticalFunctionsCollection. We would have to check that this works, with successful dictionary creation and serialization.

Looking at the documentation [1] I see an alternative approach you might want to consider. EventSetup mechanism has a way to seeing if a record has changed ( edm::ESWatcher<> ) and this can be included in a EDProducer or EDAnalyzer to trigger a function call. Maybe what is done at CTPPSOptics and CTPPSInterpolatedOptics could be made by function calls to produce the interpolated data. In such approach, the only conditions data handled through EventSetup would be LHCInfo and LHCOpticalFunctionsSet.

We can try to clarify some of these points at the AlCaDB meeting next week.  

[1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_each_time_a_Record

**Comment by wpcarvalho** [comment]
> @wpcarvalho Would it be possible to generalise as follows?
> 
> ```
> class LHCOpticalFunctionsCollection
> {
>   // map: xangle --> (map: RP id --> optical functions)
>   std::map<double, std::unordered_map<unsigned int, LHCOpticalFunctionsSet>> m_data;
> };
> ```
> In other words, can the DB store the optical functions at a variable number of crossing angle points?

All the data types are supported by Serializable.h [1], so it should work. 

[1] https://github.com/cms-sw/cmssw/blob/master/CondFormats/Serialization/interface/Serializable.h

**Comment by jan-kaspar** [comment]
> On the other hand, a CTPPSOpticsRcd would imply a CTPPSOptics DB class, which I believe would have to follow the requirements for such classes like being serializable. Probably the same is true for LHCOpticalFunctionsCollection. We would have to check that this works, with successful dictionary creation and serialization.

Why? Technically I think that the name of a record and payload class are independent. Are there some guidelines that require the relation?

> Looking at the documentation [1] I see an alternative approach you might want to consider. EventSetup mechanism has a way to seeing if a record has changed ( edm::ESWatcher<> ) and this can be included in a EDProducer or EDAnalyzer to trigger a function call. Maybe what is done at CTPPSOptics and CTPPSInterpolatedOptics could be made by function calls to produce the interpolated data. In such approach, the only conditions data handled through EventSetup would be LHCInfo and LHCOpticalFunctionsSet.

Thanks for the proposal - in fact, this is what is used at the moment. A disadvantage of this approach is that every single module needing the interpolated optics would need to (re)do the interpolation. This would lead to multiplication of identical code and repeating the same calculation.

> We can try to clarify some of these points at the AlCaDB meeting next week.

Any news from the meeting?

**Comment by wpcarvalho** [comment]
> > On the other hand, a CTPPSOpticsRcd would imply a CTPPSOptics DB class, which I believe would have to follow the requirements for such classes like being serializable. Probably the same is true for LHCOpticalFunctionsCollection. We would have to check that this works, with successful dictionary creation and serialization.
> 
> Why? Technically I think that the name of a record and payload class are independent. Are there some guidelines that require the relation?

The point is not the name. According to documentation [1,2], each data class must be associated with a EventSetup record. So, for the proposed design, the following relationship should hold:

LHCOpticalFunctionsSet  ->  LHCOpticalFunctionsSetRec
LHCOpticalFunctionsCollection  ->  LHCOpticalFunctionsCollectionRec
CTPPSOptics  ->  CTPPSOpticsRcd

Actually, which data to associate to which record (relationship) must be registered at CondCore/CTPPSPlugins/src/plugin.cc

Each of these three data classes must be serializable. 

[1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCondSystemLayout
[2] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCondObjectsTutorial

> 
> > Looking at the documentation [1] I see an alternative approach you might want to consider. EventSetup mechanism has a way to seeing if a record has changed ( edm::ESWatcher<> ) and this can be included in a EDProducer or EDAnalyzer to trigger a function call. Maybe what is done at CTPPSOptics and CTPPSInterpolatedOptics could be made by function calls to produce the interpolated data. In such approach, the only conditions data handled through EventSetup would be LHCInfo and LHCOpticalFunctionsSet.
> 
> Thanks for the proposal - in fact, this is what is used at the moment. A disadvantage of this approach is that every single module needing the interpolated optics would need to (re)do the interpolation. This would lead to multiplication of identical code and repeating the same calculation.
> 

Sorry for my ignorance, but isn't there a way to make result of the interpolation persistent until the next function call?

> > We can try to clarify some of these points at the AlCaDB meeting next week.
> 
> Any news from the meeting?

Meeting was long and PPS talks a bit compressed at the end. No comments on this specific topic involving optical functions. I felt time was short to have a reasonable discussion. I will wait for your comments and depending on our understanding (or lack of) of this issue I can try to draw some specific questions to send to the AlCaDB conveners.

**Comment by jan-kaspar** [comment]
> > > On the other hand, a CTPPSOpticsRcd would imply a CTPPSOptics DB class, which I believe would have to follow the requirements for such classes like being serializable. Probably the same is true for LHCOpticalFunctionsCollection. We would have to check that this works, with successful dictionary creation and serialization.
> > 
> > Why? Technically I think that the name of a record and payload class are independent. Are there some guidelines that require the relation?
> 
> The point is not the name. According to documentation [1,2], each data class must be associated with a EventSetup record. So, for the proposed design, the following relationship should hold:
> 
> LHCOpticalFunctionsSet -> LHCOpticalFunctionsSetRec
> LHCOpticalFunctionsCollection -> LHCOpticalFunctionsCollectionRec
> CTPPSOptics -> CTPPSOpticsRcd
> 
> Actually, which data to associate to which record (relationship) must be registered at CondCore/CTPPSPlugins/src/plugin.cc
> 
> Each of these three data classes must be serializable.
> 
> [1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCondSystemLayout
> [2] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCondObjectsTutorial

I understood from the documentation [1] and [2] that is describes the case where the data are stored in the DB. In our example, this holds for ``CTPPSOpticsRcd`` and ``LHCOpticalFunctionsCollection`` but not for ``CTPPSInterpolatedOpticsRcd`` - this would hold run-time-only data and consequently there would be no data-proxy module etc.

For the names, yes, the guidelines suggest to use the same name for the data record and class. On the other hand, it does not forbid to do otherwise. Regarding ``CTPPSOpticsRcd`` I suggest a more generic name on purpose, to keep open the possibility to use optics parametrisation instead of the optical functions. So I think there is a justification. For ``CTPPSInterpolatedOpticsRcd`` and ``LHCInterpolatedOpticalFunctionsSet`` if necessary, the same name can be used.

Coming back to the data-proxy plugin, if I understand correctly, there would be just one association:
```
CTPPSOpticsRcd <--> LHCOpticalFunctionsCollection
```
The class ``LHCOpticalFunctionsSet`` has an auxiliary role only (nevertheless reflecting the structure of the data).

In summary, I think that the proposed structure is within reasonable agreement with the guidelines. If you prefer, we can double check with relevant conveners - let me know!

> > > Looking at the documentation [1] I see an alternative approach you might want to consider. EventSetup mechanism has a way to seeing if a record has changed ( edm::ESWatcher<> ) and this can be included in a EDProducer or EDAnalyzer to trigger a function call. Maybe what is done at CTPPSOptics and CTPPSInterpolatedOptics could be made by function calls to produce the interpolated data. In such approach, the only conditions data handled through EventSetup would be LHCInfo and LHCOpticalFunctionsSet.
> > 
> > 
> > Thanks for the proposal - in fact, this is what is used at the moment. A disadvantage of this approach is that every single module needing the interpolated optics would need to (re)do the interpolation. This would lead to multiplication of identical code and repeating the same calculation.
> 
> Sorry for my ignorance, but isn't there a way to make result of the interpolation persistent until the next function call?

If the "next function call" refers to analyze/produce calls of the same plugin, then yes, this is easy and is even done in the current code. What is less obvious is to share the interpolation between different modules. And here I find the EventSetup mechanism useful (and appropriate).

**Comment by wpcarvalho** [comment]
> > > > On the other hand, a CTPPSOpticsRcd would imply a CTPPSOptics DB class, which I believe would have to follow the requirements for such classes like being serializable. Probably the same is true for LHCOpticalFunctionsCollection. We would have to check that this works, with successful dictionary creation and serialization.
> > > 
> > > 
> > > Why? Technically I think that the name of a record and payload class are independent. Are there some guidelines that require the relation?
> > 
> > 
> > The point is not the name. According to documentation [1,2], each data class must be associated with a EventSetup record. So, for the proposed design, the following relationship should hold:
> > LHCOpticalFunctionsSet -> LHCOpticalFunctionsSetRec
> > LHCOpticalFunctionsCollection -> LHCOpticalFunctionsCollectionRec
> > CTPPSOptics -> CTPPSOpticsRcd
> > Actually, which data to associate to which record (relationship) must be registered at CondCore/CTPPSPlugins/src/plugin.cc
> > Each of these three data classes must be serializable.
> > [1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCondSystemLayout
> > [2] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCondObjectsTutorial
> 
> I understood from the documentation [1] and [2] that is describes the case where the data are stored in the DB. In our example, this holds for `CTPPSOpticsRcd` and `LHCOpticalFunctionsCollection` but not for `CTPPSInterpolatedOpticsRcd` - this would hold run-time-only data and consequently there would be no data-proxy module etc.
> 
> For the names, yes, the guidelines suggest to use the same name for the data record and class. On the other hand, it does not forbid to do otherwise. Regarding `CTPPSOpticsRcd` I suggest a more generic name on purpose, to keep open the possibility to use optics parametrisation instead of the optical functions. So I think there is a justification. For `CTPPSInterpolatedOpticsRcd` and `LHCInterpolatedOpticalFunctionsSet` if necessary, the same name can be used.
> 
> Coming back to the data-proxy plugin, if I understand correctly, there would be just one association:
> 
> ```
> CTPPSOpticsRcd <--> LHCOpticalFunctionsCollection
> ```
> The class `LHCOpticalFunctionsSet` has an auxiliary role only (nevertheless reflecting the structure of the data).
> 
> In summary, I think that the proposed structure is within reasonable agreement with the guidelines. If you prefer, we can double check with relevant conveners - let me know!
> 

Your reasoning regarding `CTPPSOpticsRcd` makes sense and I understand better now what you have in mind and which data goes into the database. 

I have concerns, however, with the `CTPPSInterpolatedOpticsRcd` and `LHCInterpolatedOpticalFunctionsSet` part. I've got the impression from the documentation that even if a EventSetup record is gonna be used for run-time data, this data must follow the standards for a DB object class. See [3], in particular the requirement for the data type returned by a ESProducer:

  3. Make sure the data types you are returning have been [registered](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToRegisterESData)

If my understanding is right, `LHCInterpolatedOpticalFunctionsSet` would have to be serializable and then the problem with TSpline3 would appear again.

I think it would be wise to double check with experts!

[3] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToWriteESProducer#The_simple_way

**Comment by jan-kaspar** [comment]
Thanks again for the feedback Wagner!

> I have concerns, however, with the `CTPPSInterpolatedOpticsRcd` and `LHCInterpolatedOpticalFunctionsSet` part. I've got the impression from the documentation that even if a EventSetup record is gonna be used for run-time data, this data must follow the standards for a DB object class. See [3], in particular the requirement for the data type returned by a ESProducer:
> 
> 1. Make sure the data types you are returning have been [registered](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToRegisterESData)
> 
> If my understanding is right, `LHCInterpolatedOpticalFunctionsSet` would have to be serializable and then the problem with TSpline3 would appear again.
> 
> I think it would be wise to double check with experts!
> 
> [3] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToWriteESProducer#The_simple_way

The following link
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCondObjectsTutorial#How_to_create_a_new_conditions_D
reads: ``... The rules for the dictionary are the very same as for any other persistent class...`` Then, this link
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts#classes_def_xml_entries_for_an_E
shows how to make a class member non-serialised. So I think there is a solution.

I suggest:
  * I go ahead with implementing the proposed solution, in order not to delay #25495 any further,
  * in the meantime you double check with experts.

Can we do like this?

**Comment by wpcarvalho** [comment]
OK Jan, it sounds good to me!

**Comment by jan-kaspar** [comment]
Proposal implemented and committed to https://github.com/cms-sw/cmssw/pull/25495.
